production: &production
  username: xxxxx
  password: xxxxx

development: &development
  database: lacwrumosa_dev
  username: root
  password: sqlgshuum4s
  
test: &test
  username: root
  password: sqlgshuum4s
  
profile: &profile
  database: xxxxx
  username: xxxxx
  password: xxxxx
